#!/bin/sh

run() {
    ./false_int $*
}

pass() {
    echo "PASS: $*"
}

fail() {
    echo "FAIL: $*"
    exit 1
}

good() {
    run $* || fail $*
    pass $*
}

bad() {
    run $* && fail $*
    pass $*
}

make || exit

bad  tests/bad_char.f
bad  tests/bad_comment.f
bad  tests/bad_comment_close.f
bad  tests/bad_symbol.f
bad  tests/div_zero.f

bad  tests/empty.f $(seq 2 27)
good tests/empty.f
good tests/char.f

good tests/basic.f

bad  --extensions tests/builtin-assert-bad.f
good --extensions tests/builtin-assert-good.f
good --extensions tests/extended.f

good tests/add.f 3 4
good tests/factorial.f
good tests/factorialv2.f
good tests/gcd.f
good tests/gcdv2.f
good tests/head.f < makefile
good tests/logical.f
good tests/sierpinski.f 3
good tests/tail.f < makefile

# https://strlen.com/files/lang/false/False12b.zip
PROGRAM="False12b/contrib/Herb_Wollman/Translate.f"
if [ -f "${PROGRAM}" ]
then
    # ISO-8859 text
    echo abcABC | LC_ALL="en_US.ISO-8859" ./false_int "${PROGRAM}" --input "065 066" | grep -q abcBBC || fail "${PROGRAM}"
    pass "${PROGRAM}"
fi
